#!/bin/bash

while :; do

batTime=$(acpi | awk '/Battery/ { print "("$5")" }' ) # Time left
batVal=$(acpi | awk '/Battery/ { print $4 }' | tr -d ',') # Battery percentage
batValNumeric=$(acpi | awk '/Battery/ { print $4 }' | tr -d ',' | tr -d '%' )

if [ "$batValNumeric" -le "100" -a "$batValNumeric" -gt "70" ];
	then batColor="#00bc0d";
elif [ "$batValNumeric" -lt "30" ];
	then batColor="#bc1d00";
else batColor="#1d99bc";
fi

if [ "$batTime" = "()" ];
	then printf '{"full_text":"Charged", "border":"%s"}\n' "$batColor"
else
    #echo $batVal $batTime;
	printf '{"full_text":"%s %s", "border":"%s"}\n' "$batVal" "$batTime" "$batColor";
fi;

sleep 1;
done
