#!/bin/bash

while :; do

tempNumeric=$(sensors coretemp-isa-0000 | awk '/Physical/ { print $4 }' | tr -d '+' | tr -d '.0°C' )

if [ "$tempNumeric" -gt 55 ];
	then printf '{"full_text":"", "color":"#bc1d00", "border":"#bc1d00"}\n';
else
	printf '{"full_text":""}\n';
fi;
sleep 1;
done
