#!/bin/bash

while :; do
volVal=$(amixer get Master | awk '/Front Left:/ { print $5 }' | awk '/%/' | tr -d '[]')
volMute=$(amixer get Master | awk '/Front Left:/ { print $6 }' | tr -d '[]')

if [ "$volMute" = "off" ]
	#then echo -e '{"full_text": \""$volVal"\", "border": "#bc1d00"}'
	then printf '{"full_text":"%s", "border": "#bc1d00"}\n' "$volVal"
else
	echo '{"full_text": "test2"}'
	printf '{"full_text":"%s"}\n' "$volVal"
fi;
sleep 1;
done
