#!/bin/bash

while :; do
volVal=$(amixer get Master | awk '/Front Left:/ { print $5 }' | awk '/%/' | tr -d '[]')
volMute=$(amixer get Master | awk '/Front Left:/ { print $6 }' | tr -d '[]')

if [ "$volMute" = "off" ]
	then printf '{"full_text":"%s", "border": "#bc1d00"}\n' "$volVal"
else
	printf '{"full_text":"%s"}\n' "$volVal"
fi;
sleep 1;
done
