#!/bin/bash

while :; do
volVal=$(amixer get Master | awk '/Front Left:/ { print $5 }' | awk '/%/' | tr -d '[]' | tr -d '%')
volMute=$(amixer get Master | awk '/Front Left:/ { print $6 }' | tr -d '[]')

if [ "$volMute" = "off" ]
then 
	volColor="#bc1d00"
else
	volColor="#1d99bc"
fi

if [ "$volVal" -le 30 ];
then printf '{"full_text":" ", "color":"%s", "border":"%s"}\n' "$volColor" "$volColor"

elif [ "$volVal" -le 70 ];
then printf '{"full_text":" ", "color":"%s", "border":"%s"}\n' "$volColor" "$volColor"

elif [ "$volVal" -le 100 ];
then printf '{"full_text":"", "color":"%s", "border":"%s"}\n' "$volColor" "$volColor"

fi;
sleep 1;
done
