#!/bin/sh

INTERFACE="${1:-wlan0}"

state="$(cat /sys/class/net/$INTERFACE/operstate)"

if [ "$state" != "up" ]; then
	echo "down"
	echo "down"
	echo "#FF0000"
	exit 0
fi

speed="$(cat /sys/class/net/$INTERFACE/speed 2> /dev/null)"

ipaddr="$(ip addr show $INTERFACE | perl -n -e'/inet (.+)\// && print $1')"
ipaddr="${ipaddr:-0.0.0.0}"

# full text
echo -n "$ipaddr"
[ -n "$speed" ] && echo " ($speed Mbits/s)" || echo

# short text
echo "$ipaddr"
