#!/bin/bash


volVal=$(amixer get Master | awk '/Mono/ { print $4 }' | awk '/%/' | tr -d '[]' | tr -d '%')

if [ $(amixer get Master | awk '/Mono/ { print $6 }' | tr -d '[]') == "off" ]
    then echo "Mute" #bc1d00
elif [ "$volVal" -le 25 ];
    then echo "";
elif [ "$volVal" -le 70 ];
    then echo "";
elif [ "$volVal" -le 100 ];
    then echo "";
fi
